export const sectors = [
  'Education',
  'Health',
  'Finance, Trade & Business Environments',
  'Agriculture',
  'Environment: Water, Climate Change, Biodiversity, Forestry',
  'Security',
  'Social/ Welfare Programmes',
  'Culture & Entertainment',
  'Technology and Communications',
  'Natural Minerals/ Mining',
  'Youth and Sports',
  'Women, Gender Issues',
  'Children and Family',
  'Transportation',
  'International Relations & Partnerships',
  'Oil & Gas',
  'Power',
  'Land, Works & Housing',
  'Kwara Issues',
];
